"use client";

import { FormEvent, useEffect, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import { daysUntil, type Contract } from "@/lib/living-data";
import { createBrowserClient } from "@/lib/supabase/client";
import { Empty } from "./fixed-costs";

type ContractInput = Omit<Contract, "id" | "created_at">;
const blank: ContractInput = { name: "", start_date: "", end_date: "", memo: "" };

export function Contracts() {
  const [items, setItems] = useState<Contract[]>([]); const [form, setForm] = useState<ContractInput>(blank);
  const [editingId, setEditingId] = useState<string | null>(null); const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { const supabase = createBrowserClient(); if (!supabase) return; const { data, error } = await supabase.from("contracts").select("*").order("end_date"); if (error) setMessage("데이터를 불러오지 못했어요. 데이터베이스 설정을 확인해 주세요."); else setItems((data ?? []) as Contract[]); setLoading(false); };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  function create() { setForm(blank); setEditingId(null); setMessage(""); setOpen(true); }
  function edit(item: Contract) { setForm({ name: item.name, start_date: item.start_date, end_date: item.end_date, memo: item.memo }); setEditingId(item.id); setMessage(""); setOpen(true); }
  async function save(event: FormEvent) { event.preventDefault(); setMessage(""); if (form.end_date < form.start_date) { setMessage("만료일은 시작일보다 빠를 수 없어요."); return; } const supabase = createBrowserClient(); if (!supabase) return; const payload = { ...form, name: form.name.trim(), memo: form.memo?.trim() || null }; const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { setMessage("로그인 정보를 확인할 수 없어요. 다시 로그인해 주세요."); return; } const result = editingId ? await supabase.from("contracts").update(payload).eq("id", editingId) : await supabase.from("contracts").insert({ ...payload, user_id: auth.user.id }); if (result.error) { setMessage(result.error.message); return; } setOpen(false); load(); }
  async function remove(id: string) { if (!window.confirm("이 계약 일정을 삭제할까요?")) return; const supabase = createBrowserClient(); if (!supabase) return; const { error } = await supabase.from("contracts").delete().eq("id", id); if (error) setMessage(error.message); else load(); }
  return <section><header className="page-header"><div><p className="eyebrow">계약 일정</p><h1>중요한 만료일을 놓치지 마세요.</h1><p>주거와 생활 계약을 한 곳에서 확인할 수 있어요.</p></div><button className="primary-button" onClick={create}><Plus size={18} />계약 추가</button></header>{message && !open && <p className="inline-message">{message}</p>}<section className="content-card">{loading ? <p className="empty-state">불러오는 중이에요.</p> : items.length === 0 ? <Empty title="아직 등록한 계약이 없어요." description="월세, 인터넷, 보험 등 만료일을 챙길 계약을 추가해 보세요." action={create} /> : <div className="contract-list">{items.map((item) => { const remaining = daysUntil(item.end_date); return <article className="contract-row" key={item.id}><div className="contract-date"><strong>{new Date(`${item.end_date}T00:00:00`).getDate()}</strong><span>{new Date(`${item.end_date}T00:00:00`).toLocaleDateString("ko-KR", { month: "short" })}</span></div><div className="contract-info"><h2>{item.name}</h2><p>{item.start_date.replaceAll("-", ".")} — {item.end_date.replaceAll("-", ".")}</p>{item.memo && <small>{item.memo}</small>}</div><span className={remaining < 0 ? "deadline passed" : remaining <= 30 ? "deadline soon" : "deadline"}>{remaining < 0 ? "만료됨" : remaining === 0 ? "오늘 만료" : `${remaining}일 남음`}</span><div className="row-actions"><button aria-label={`${item.name} 수정`} onClick={() => edit(item)}><Pencil size={16} /></button><button aria-label={`${item.name} 삭제`} onClick={() => remove(item.id)}><Trash2 size={16} /></button></div></article>; })}</div>}</section>{open && <div className="modal-backdrop"><form className="modal" onSubmit={save}><header><div><p className="eyebrow">{editingId ? "계약 수정" : "새 계약"}</p><h2>{editingId ? "계약 정보를 수정하세요." : "챙길 계약을 추가하세요."}</h2></div><button className="icon-button" type="button" onClick={() => setOpen(false)}><X /></button></header><div className="form-grid"><label>계약 이름<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="예: 전세 계약" required maxLength={80} /></label><label>시작일<input type="date" value={form.start_date} onChange={(e) => setForm({ ...form, start_date: e.target.value })} required /></label><label>만료일<input type="date" value={form.end_date} onChange={(e) => setForm({ ...form, end_date: e.target.value })} required /></label><label className="wide-field">메모 (선택)<textarea value={form.memo ?? ""} onChange={(e) => setForm({ ...form, memo: e.target.value })} maxLength={500} placeholder="갱신 조건, 연락처 등 필요한 메모를 남겨 보세요." /></label></div>{message && <p className="form-error">{message}</p>}<footer><button className="secondary-button" type="button" onClick={() => setOpen(false)}>취소</button><button className="primary-button" type="submit">{editingId ? "저장하기" : "추가하기"}</button></footer></form></div>}</section>;
}
