"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, CalendarClock, ReceiptText, WalletCards } from "lucide-react";
import { daysUntil, formatWon, monthKey, monthlyAmount, type Contract, type FixedCost, type MonthlyTask } from "@/lib/living-data";
import { createBrowserClient } from "@/lib/supabase/client";

export function Dashboard() {
  const [costs, setCosts] = useState<FixedCost[]>([]); const [contracts, setContracts] = useState<Contract[]>([]); const [tasks, setTasks] = useState<MonthlyTask[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { const load = async () => { const supabase = createBrowserClient(); if (!supabase) return; const [costResult, contractResult, taskResult] = await Promise.all([supabase.from("fixed_costs").select("*").order("payment_day"), supabase.from("contracts").select("*").order("end_date"), supabase.from("monthly_tasks").select("*").eq("month", monthKey()).eq("is_completed", false)]); setCosts((costResult.data ?? []) as FixedCost[]); setContracts((contractResult.data ?? []) as Contract[]); setTasks((taskResult.data ?? []) as MonthlyTask[]); setLoading(false); }; const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const total = costs.reduce((sum, cost) => sum + monthlyAmount(cost), 0); const categories = Object.entries(costs.reduce<Record<string, number>>((map, cost) => { map[cost.category] = (map[cost.category] ?? 0) + monthlyAmount(cost); return map; }, {})).sort((a, b) => b[1] - a[1]); const upcoming = contracts.filter((item) => daysUntil(item.end_date) <= 90).slice(0, 3);
  const month = new Intl.DateTimeFormat("ko-KR", { month: "long" }).format(new Date());
  return <section><header className="page-header dashboard-header"><div><p className="eyebrow">{month} 생활 관리판</p><h1>이번 달, 어디에 얼마가 나갈까요?</h1><p>고정비와 가까운 계약 일정을 한눈에 점검하세요.</p></div></header>{loading ? <div className="page-loading">대시보드를 불러오는 중이에요.</div> : <><div className="summary-grid"><article className="summary-card strong"><span className="summary-icon"><WalletCards size={20} /></span><p>월 예상 고정비</p><strong>{formatWon(total)}</strong><small>등록한 {costs.length}개 항목 기준</small></article><article className="summary-card"><span className="summary-icon"><ReceiptText size={20} /></span><p>이번 달 확인할 일</p><strong>{tasks.length}건</strong><small>{tasks.length ? "월간 리포트에서 완료 처리하세요" : "월간 리포트에서 생성할 수 있어요"}</small></article><article className="summary-card"><span className="summary-icon"><CalendarClock size={20} /></span><p>90일 내 만료 계약</p><strong>{upcoming.length}건</strong><small>{upcoming[0] ? `${upcoming[0].name} ${daysUntil(upcoming[0].end_date)}일 남음` : "예정된 일정이 없어요"}</small></article></div><div className="dashboard-grid"><section className="content-card category-card"><header className="card-header"><div><h2>카테고리별 고정비</h2><p>월 환산 금액 기준</p></div><Link href="/costs">전체 보기 <ArrowRight size={15} /></Link></header>{categories.length === 0 ? <Blank link="/costs" label="고정비를 추가해 월 지출을 확인해 보세요." /> : <div className="category-list">{categories.map(([category, amount]) => <div key={category}><div className="category-label"><span><i className={`category-dot category-${category}`} />{category}</span><b>{formatWon(amount)}</b></div><div className="bar"><i style={{ width: `${Math.max(5, (amount / total) * 100)}%` }} /></div></div>)}</div>}</section><section className="content-card schedule-card"><header className="card-header"><div><h2>확인할 계약 일정</h2><p>가까운 만료일 순</p></div><Link href="/contracts">전체 보기 <ArrowRight size={15} /></Link></header>{upcoming.length === 0 ? <Blank link="/contracts" label="챙길 계약 일정을 추가해 보세요." /> : <div className="mini-schedule">{upcoming.map((item) => <article key={item.id}><div><strong>{item.name}</strong><p>{item.end_date.replaceAll("-", ".")} 만료</p></div><span className={daysUntil(item.end_date) <= 30 ? "deadline soon" : "deadline"}>{daysUntil(item.end_date) < 0 ? "만료됨" : `${daysUntil(item.end_date)}일`}</span></article>)}</div>}</section></div></>}</section>;
}

function Blank({ link, label }: { link: string; label: string }) { return <div className="compact-empty"><p>{label}</p><Link href={link} className="secondary-button">추가하기</Link></div>; }
