"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, Check, ClipboardCheck, Plus } from "lucide-react";
import { daysUntil, formatMonth, formatWon, monthKey, monthlyAmount, type Contract, type FixedCost, type MonthlyReport, type MonthlyTask, type Subscription } from "@/lib/living-data";
import { createBrowserClient } from "@/lib/supabase/client";

type Data = { reports: MonthlyReport[]; tasks: MonthlyTask[]; costs: FixedCost[]; subscriptions: Subscription[]; contracts: Contract[] };

export function Reports() {
  const [data, setData] = useState<Data>({ reports: [], tasks: [], costs: [], subscriptions: [], contracts: [] });
  const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [busy, setBusy] = useState<"report" | "tasks" | null>(null);
  const currentMonth = monthKey();
  const load = async () => { const supabase = createBrowserClient(); if (!supabase) return; const [reports, tasks, costs, subscriptions, contracts] = await Promise.all([supabase.from("monthly_reports").select("*").order("month", { ascending: false }), supabase.from("monthly_tasks").select("*").eq("month", currentMonth).order("is_completed").order("due_date"), supabase.from("fixed_costs").select("*").order("payment_day"), supabase.from("subscriptions").select("*").eq("is_active", true).order("billing_day"), supabase.from("contracts").select("*").order("end_date")]); const failed = [reports, tasks, costs, subscriptions, contracts].find((result) => result.error); if (failed?.error) setMessage("데이터를 불러오지 못했어요. 3단계 데이터베이스 마이그레이션이 적용됐는지 확인해 주세요."); setData({ reports: (reports.data ?? []) as MonthlyReport[], tasks: (tasks.data ?? []) as MonthlyTask[], costs: (costs.data ?? []) as FixedCost[], subscriptions: (subscriptions.data ?? []) as Subscription[], contracts: (contracts.data ?? []) as Contract[] }); setLoading(false); };
  // The first load only needs the month captured when this screen is mounted.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const currentTotal = useMemo(() => data.costs.reduce((sum, cost) => sum + monthlyAmount(cost), 0) + data.subscriptions.reduce((sum, item) => sum + item.amount, 0), [data]);
  const currentReport = data.reports.find((report) => report.month === currentMonth);
  const previousReport = data.reports.find((report) => report.month < currentMonth);
  const change = currentReport && previousReport ? currentReport.total - previousReport.total : null;
  const chartReports = [...data.reports].slice(0, 6).reverse(); const chartMax = Math.max(...chartReports.map((item) => item.total), 1);
  async function createReport() { setBusy("report"); setMessage(""); const supabase = createBrowserClient(); if (!supabase) return; const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { setBusy(null); setMessage("로그인 정보를 확인할 수 없어요."); return; } const fixedCostTotal = data.costs.reduce((sum, cost) => sum + monthlyAmount(cost), 0); const subscriptionTotal = data.subscriptions.reduce((sum, item) => sum + item.amount, 0); const { error } = await supabase.from("monthly_reports").upsert({ user_id: auth.user.id, month: currentMonth, fixed_cost_total: fixedCostTotal, subscription_total: subscriptionTotal, total: fixedCostTotal + subscriptionTotal }, { onConflict: "user_id,month" }); if (error) setMessage(error.message); else { setMessage("이번 달 리포트를 저장했어요. 이후 금액이 바뀌면 다시 생성해 최신 값으로 갱신할 수 있어요."); await load(); } setBusy(null); }
  async function createTasks() { setBusy("tasks"); setMessage(""); const supabase = createBrowserClient(); if (!supabase) return; const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { setBusy(null); return; } const yearMonth = currentMonth.slice(0, 7); const rows = [ ...data.costs.filter((item) => !item.is_autopay).map((item) => ({ user_id: auth.user!.id, title: `${item.name} 직접 결제 확인`, task_type: "payment", due_date: `${yearMonth}-${String(item.payment_day).padStart(2, "0")}`, source_key: `cost-${item.id}`, month: currentMonth })), ...data.subscriptions.map((item) => ({ user_id: auth.user!.id, title: `${item.name} 구독 결제 확인`, task_type: "subscription", due_date: `${yearMonth}-${String(item.billing_day).padStart(2, "0")}`, source_key: `subscription-${item.id}`, month: currentMonth })), ...data.contracts.filter((item) => { const remain = daysUntil(item.end_date); return remain >= 0 && remain <= 90; }).map((item) => ({ user_id: auth.user!.id, title: `${item.name} 계약 만료 확인`, task_type: "contract", due_date: item.end_date, source_key: `contract-${item.id}`, month: currentMonth })) ]; if (rows.length === 0) { setMessage("생성할 확인할 일이 없어요. 직접 결제 고정비, 사용 중인 구독 또는 90일 내 계약을 등록해 보세요."); setBusy(null); return; } const { error } = await supabase.from("monthly_tasks").upsert(rows, { onConflict: "user_id,source_key,month", ignoreDuplicates: true }); if (error) setMessage(error.message); else { setMessage(`${rows.length}개의 확인할 일을 준비했어요.`); await load(); } setBusy(null); }
  async function toggleTask(task: MonthlyTask) { const supabase = createBrowserClient(); if (!supabase) return; const { error } = await supabase.from("monthly_tasks").update({ is_completed: !task.is_completed }).eq("id", task.id); if (error) setMessage(error.message); else await load(); }
  return <section><header className="page-header"><div><p className="eyebrow">월간 리포트</p><h1>이번 달 고정 지출을 점검하세요.</h1><p>월별 스냅샷과 확인할 일을 남겨 다음 달과 비교할 수 있어요.</p></div><div className="header-actions"><button className="secondary-button" onClick={createTasks} disabled={busy !== null}><ClipboardCheck size={16} />확인할 일 생성</button><button className="primary-button" onClick={createReport} disabled={busy !== null}><Plus size={17} />{currentReport ? "이번 달 리포트 갱신" : "이번 달 리포트 생성"}</button></div></header>{message && <p className="inline-message report-message">{message}</p>}{loading ? <div className="page-loading">리포트를 불러오는 중이에요.</div> : <><div className="report-summary"><article className="summary-card strong"><span className="summary-icon"><BarChart3 size={20} /></span><p>현재 월 예상 지출</p><strong>{formatWon(currentTotal)}</strong><small>고정비와 사용 중인 구독 기준</small></article><article className="summary-card"><p>저장된 이번 달 리포트</p><strong>{currentReport ? formatWon(currentReport.total) : "아직 없어요"}</strong><small>{currentReport ? `${formatMonth(currentReport.month)} 스냅샷` : "생성하면 비교가 시작됩니다"}</small></article><article className="summary-card"><p>지난 리포트 대비</p><strong>{change === null ? "비교할 리포트 없음" : `${change > 0 ? "+" : ""}${formatWon(change)}`}</strong><small>{previousReport ? `${formatMonth(previousReport.month)} 기준` : "월별 리포트 2개부터 비교됩니다"}</small></article></div><div className="report-grid"><section className="content-card chart-card"><header className="card-header"><div><h2>월별 고정 지출 비교</h2><p>리포트를 생성한 시점의 금액 기준</p></div></header>{chartReports.length === 0 ? <div className="compact-empty"><p>첫 리포트를 생성하면 월별 비교가 표시됩니다.</p></div> : <div className="report-chart">{chartReports.map((item) => <div className="chart-column" key={item.id}><span>{formatWon(item.total)}</span><i style={{ height: `${Math.max(10, (item.total / chartMax) * 160)}px` }} /><b>{new Date(`${item.month}T00:00:00`).getMonth() + 1}월</b></div>)}</div>}</section><section className="content-card task-card"><header className="card-header"><div><h2>이번 달 확인할 일</h2><p>{data.tasks.filter((task) => !task.is_completed).length}개 남음</p></div></header>{data.tasks.length === 0 ? <div className="compact-empty"><p>확인할 일 생성을 눌러 이번 달 항목을 준비하세요.</p></div> : <div className="task-list">{data.tasks.map((task) => <label className={task.is_completed ? "task done" : "task"} key={task.id}><input type="checkbox" checked={task.is_completed} onChange={() => void toggleTask(task)} /><span><strong>{task.title}</strong><small>{task.due_date ? `${task.due_date.replaceAll("-", ".")}까지` : "날짜 미정"}</small></span>{task.is_completed && <Check size={16} />}</label>)}</div>}</section></div></>}</section>;
}
