"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import { formatWon, SUBSCRIPTION_CATEGORIES, type Subscription } from "@/lib/living-data";
import { createBrowserClient } from "@/lib/supabase/client";
import { Empty } from "./fixed-costs";

type SubscriptionInput = Omit<Subscription, "id" | "created_at">;
const blank: SubscriptionInput = { name: "", amount: 0, billing_day: 1, category: "영상", is_active: true };

export function Subscriptions() {
  const [items, setItems] = useState<Subscription[]>([]); const [form, setForm] = useState<SubscriptionInput>(blank);
  const [editingId, setEditingId] = useState<string | null>(null); const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const activeTotal = useMemo(() => items.filter((item) => item.is_active).reduce((sum, item) => sum + item.amount, 0), [items]);
  const load = async () => { const supabase = createBrowserClient(); if (!supabase) return; const { data, error } = await supabase.from("subscriptions").select("*").order("billing_day").order("created_at"); if (error) setMessage("데이터를 불러오지 못했어요. 데이터베이스 설정을 확인해 주세요."); else setItems((data ?? []) as Subscription[]); setLoading(false); };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  function create() { setForm(blank); setEditingId(null); setMessage(""); setOpen(true); }
  function edit(item: Subscription) { setForm({ name: item.name, amount: item.amount, billing_day: item.billing_day, category: item.category, is_active: item.is_active }); setEditingId(item.id); setMessage(""); setOpen(true); }
  async function save(event: FormEvent) { event.preventDefault(); setMessage(""); if (!Number.isInteger(form.amount) || form.amount < 1) { setMessage("금액은 1원 이상의 정수로 입력해 주세요."); return; } const supabase = createBrowserClient(); if (!supabase) return; const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { setMessage("로그인 정보를 확인할 수 없어요. 다시 로그인해 주세요."); return; } const payload = { ...form, name: form.name.trim() }; const result = editingId ? await supabase.from("subscriptions").update(payload).eq("id", editingId) : await supabase.from("subscriptions").insert({ ...payload, user_id: auth.user.id }); if (result.error) { setMessage(result.error.message); return; } setOpen(false); await load(); }
  async function remove(id: string) { if (!window.confirm("이 구독을 삭제할까요?")) return; const supabase = createBrowserClient(); if (!supabase) return; const { error } = await supabase.from("subscriptions").delete().eq("id", id); if (error) setMessage(error.message); else await load(); }
  return <section><header className="page-header"><div><p className="eyebrow">구독 관리</p><h1>반복 결제를 한곳에 모으세요.</h1><p>사용 중인 구독만 월 합계에 반영됩니다.</p></div><button className="primary-button" onClick={create}><Plus size={18} />구독 추가</button></header><div className="subscription-summary"><span>활성 구독 {items.filter((item) => item.is_active).length}건</span><strong>월 {formatWon(activeTotal)}</strong></div>{message && !open && <p className="inline-message">{message}</p>}<section className="content-card">{loading ? <p className="empty-state">불러오는 중이에요.</p> : items.length === 0 ? <Empty title="아직 등록한 구독이 없어요." description="영상, 음악, 클라우드 서비스처럼 반복 결제되는 항목을 추가해 보세요." action={create} /> : <div className="data-table"><div className="table-row subscription-head table-head"><span>서비스</span><span>카테고리</span><span>결제일</span><span>상태</span><span>월 금액</span><span /></div>{items.map((item) => <div className="table-row subscription-head" key={item.id}><strong>{item.name}</strong><span>{item.category}</span><span>매월 {item.billing_day}일</span><span><i className={item.is_active ? "status active" : "status"}>{item.is_active ? "사용 중" : "중지"}</i></span><b>{formatWon(item.amount)}</b><span className="row-actions"><button aria-label={`${item.name} 수정`} onClick={() => edit(item)}><Pencil size={16} /></button><button aria-label={`${item.name} 삭제`} onClick={() => remove(item.id)}><Trash2 size={16} /></button></span></div>)}</div>}</section>{open && <SubscriptionModal form={form} setForm={setForm} editing={Boolean(editingId)} onClose={() => setOpen(false)} onSave={save} message={message} />}</section>;
}

function SubscriptionModal({ form, setForm, editing, onClose, onSave, message }: { form: SubscriptionInput; setForm: React.Dispatch<React.SetStateAction<SubscriptionInput>>; editing: boolean; onClose: () => void; onSave: (event: FormEvent) => void; message: string }) {
  const field = <K extends keyof SubscriptionInput>(key: K, value: SubscriptionInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="modal-backdrop" role="presentation"><form className="modal" onSubmit={onSave}><header><div><p className="eyebrow">{editing ? "구독 수정" : "새 구독"}</p><h2>{editing ? "구독 정보를 수정하세요." : "반복 결제를 추가하세요."}</h2></div><button type="button" className="icon-button" onClick={onClose}><X /></button></header><div className="form-grid"><label>서비스 이름<input value={form.name} onChange={(e) => field("name", e.target.value)} placeholder="예: 넷플릭스" required maxLength={80} /></label><label>월 금액 (원)<input type="number" min="1" step="1" value={form.amount || ""} onChange={(e) => field("amount", Number(e.target.value))} required /></label><label>결제일<select value={form.billing_day} onChange={(e) => field("billing_day", Number(e.target.value))}>{Array.from({ length: 31 }, (_, i) => i + 1).map((day) => <option value={day} key={day}>{day}일</option>)}</select></label><label>카테고리<select value={form.category} onChange={(e) => field("category", e.target.value as SubscriptionInput["category"])}>{SUBSCRIPTION_CATEGORIES.map((value) => <option key={value}>{value}</option>)}</select></label><label className="check-field"><input type="checkbox" checked={form.is_active} onChange={(e) => field("is_active", e.target.checked)} />현재 사용 중인 구독이에요</label></div>{message && <p className="form-error">{message}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary-button" type="submit">{editing ? "저장하기" : "추가하기"}</button></footer></form></div>;
}
